// frontend/src/app/layouts/AppLayout.vue
<script setup lang="ts">
import { MoonIcon, SunIcon } from "@lucide/vue"
import { RouterView, useRoute } from "vue-router"

import AppSidebar from "@/app/layouts/AppSidebar.vue"
import { useThemeStore } from "@/app/themeStore"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { useAuthStore } from "@/features/auth/store"

const appStore = useThemeStore()
const authStore = useAuthStore()
const route = useRoute()
</script>

<template>
  <SidebarProvider>
    <AppSidebar />
    <SidebarInset>
      <header class="bg-background sticky top-0 z-10 flex h-14 shrink-0 items-center gap-2 border-b px-4">
        <SidebarTrigger class="-ml-1" />
        <Separator
          class="mr-1 data-[orientation=vertical]:h-4 data-[orientation=vertical]:self-center"
          orientation="vertical"
        />
        <h1 class="flex-1 truncate text-sm font-medium">{{ route.meta.title ?? "" }}</h1>
        <Button aria-label="切换主题" size="icon-sm" variant="ghost" @click="appStore.setDark(!appStore.isDark)">
          <SunIcon v-if="appStore.isDark" />
          <MoonIcon v-else />
        </Button>
      </header>
      <div class="flex flex-1 flex-col gap-4 p-4">
        <RouterView v-slot="{ Component }">
          <!-- 按上层组件身份缓存，不使用叶子路由名；账号变化时整体清空。 -->
          <KeepAlive :key="authStore.pageRevision">
            <component :is="Component" />
          </KeepAlive>
        </RouterView>
      </div>
    </SidebarInset>
  </SidebarProvider>
</template>

// ui/src/components/app/app-layout.tsx
import { Outlet } from "react-router-dom"

import { AppSidebar } from "@/components/app/app-sidebar.tsx"
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar.tsx"
import { Separator } from "@/components/ui/separator.tsx"
import { useEffect, useState } from "react";
import { Moon, Sun } from "lucide-react";
import { Switch } from "@/components/ui/switch.tsx";

export function AppLayout() {
    return (
        <SidebarProvider className="relative min-h-screen bg-background">
            <AppSidebar/>

            <SidebarInset className="relative bg-transparent">
                <div className="relative grid min-h-svh w-full grid-rows-[auto_1fr]">
                    <header
                        className="sticky top-0 z-10 border-b border-border/70 bg-background/90 backdrop-blur supports-backdrop-filter:bg-background/80">
                        <div className="flex items-center justify-between gap-3 px-6 py-4">
                            <div className="flex min-w-0 items-center gap-3">
                                <SidebarTrigger className="-ml-1"/>
                                <div className="text-sm text-muted-foreground">
                                    Java API · 控制台
                                </div>
                                <Separator className="mx-1 hidden h-4 w-px sm:block" orientation="vertical"/>
                                <div className="truncate text-sm text-muted-foreground">
                                    React Router · shadcn/ui · Tailwind
                                </div>
                            </div>
                            <ThemeToggle/>
                        </div>
                    </header>

                    <main className="min-w-0 px-6 py-6">
                        <Outlet/>
                    </main>
                </div>
            </SidebarInset>
        </SidebarProvider>
    )
}

function ThemeToggle() {
    const [isDark, setIsDark] = useState(false)

    useEffect(() => {
        setIsDark(document.documentElement.classList.contains("dark"))
    }, [])

    function handleCheckedChange(checked: boolean) {
        document.documentElement.classList.toggle("dark", checked)
        setIsDark(checked)
    }

    return (
        <div className="flex items-center gap-2">
            <Sun
                aria-hidden="true"
                className={isDark ? "text-muted-foreground/60" : "text-foreground"}
            />
            <Switch
                aria-label="亮暗主题切换"
                checked={isDark}
                onCheckedChange={handleCheckedChange}
            />
            <Moon
                aria-hidden="true"
                className={isDark ? "text-foreground" : "text-muted-foreground/60"}
            />
        </div>
    )
}
