// ui/src/components/app/app-sidebar.tsx
import { matchPath, NavLink, useLocation } from "react-router-dom"
import { CalendarDays, Gauge } from "lucide-react"
import {
    Sidebar,
    SidebarContent,
    SidebarGroup,
    SidebarGroupContent,
    SidebarHeader,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from "@/components/ui/sidebar"

type NavItem = {
    to: string
    label: string
    Icon: typeof Gauge
    end?: boolean
}

const navItems: NavItem[] = [
    { to: "/holiday", label: "节假日", Icon: CalendarDays },
]

export function AppSidebar() {
    const location = useLocation()

    return (
        <Sidebar collapsible="icon">
            <SidebarHeader>
                <SidebarMenu>
                    <SidebarMenuItem>
                        <SidebarMenuButton asChild size="lg" tooltip="控制台">
                            <NavLink to="/holiday" end>
                                <div
                                    className="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg text-xs font-semibold"
                                    aria-hidden="true"
                                >
                                    API
                                </div>
                                <div
                                    className="grid flex-1 text-left text-sm leading-tight group-data-[collapsible=icon]:hidden">
                                    <span className="truncate font-medium">控制台</span>
                                    <span className="truncate text-xs text-sidebar-foreground/70">Java API</span>
                                </div>
                            </NavLink>
                        </SidebarMenuButton>
                    </SidebarMenuItem>
                </SidebarMenu>
            </SidebarHeader>

            <SidebarContent>
                <SidebarGroup>
                    <SidebarGroupContent>
                        <SidebarMenu>
                            {navItems.map((item) => {
                                const isActive = !!matchPath(
                                    { path: item.to, end: item.end ?? false },
                                    location.pathname,
                                )

                                return (
                                    <SidebarMenuItem key={item.to}>
                                        <SidebarMenuButton asChild isActive={isActive} tooltip={item.label}>
                                            <NavLink to={item.to} end={item.end}>
                                                <item.Icon aria-hidden="true"/>
                                                <span>{item.label}</span>
                                            </NavLink>
                                        </SidebarMenuButton>
                                    </SidebarMenuItem>
                                )
                            })}
                        </SidebarMenu>
                    </SidebarGroupContent>
                </SidebarGroup>
            </SidebarContent>
        </Sidebar>
    )
}

// frontend/src/layouts/AppSidebar.vue
<script setup lang="ts">
import { ZapIcon } from "@lucide/vue"
import { watch } from "vue"
import { RouterLink, useRoute, useRouter } from "vue-router"

import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarRail,
  useSidebar,
} from "@/components/ui/sidebar"
import { getNavigationItems } from "@/layouts/navigation"

const route = useRoute()
const items = getNavigationItems(useRouter())
const { setOpenMobile } = useSidebar()
/* 移动端选中目标页面后收起抽屉。 */
watch(
  () => route.fullPath,
  () => setOpenMobile(false),
)

function isActive(name: string) {
  return route.matched.some((record) => record.name === name)
}
</script>

<template>
  <Sidebar collapsible="icon">
    <SidebarHeader>
      <SidebarMenu>
        <SidebarMenuItem>
          <SidebarMenuButton as-child size="lg">
            <RouterLink to="/">
              <div
                class="bg-sidebar-primary text-sidebar-primary-foreground flex aspect-square size-8 items-center justify-center rounded-lg"
              >
                <ZapIcon class="size-4" />
              </div>
              <span class="truncate font-semibold">MyAPI</span>
            </RouterLink>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </SidebarMenu>
    </SidebarHeader>
    <SidebarContent>
      <SidebarGroup>
        <SidebarGroupLabel>导航</SidebarGroupLabel>
        <SidebarGroupContent>
          <SidebarMenu>
            <SidebarMenuItem v-for="item in items" :key="item.name">
              <SidebarMenuButton as-child :is-active="isActive(item.name)" :tooltip="item.label">
                <RouterLink :to="{ name: item.name }">
                  <component :is="item.icon" />
                  <span>{{ item.label }}</span>
                </RouterLink>
              </SidebarMenuButton>
            </SidebarMenuItem>
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>
    </SidebarContent>
    <SidebarRail />
  </Sidebar>
</template>
